void ten(int);
void eleven(void);
void twelfth(int num);
void thirteen(void);
void fourteen(void);
void fifteen(int number);
void sixteen(int number);
void seventeen(int number);
void eighteen(void);
void nineteen(void);