void twenty(int number);
void twentyOne(int number);
void twentyTwo();
void twentyThree(int);
void twentyFour(int);
void twentyFive(int);
void twentySix(int);
void twentySeven(int);
void twentyEight(int);
void twentyNine(unsigned long long int);