void one(int);
void two(int);
void three(long long);
void four(int);
void five(int);
void six(int);
void seven(int);
void eight(int);
void nine(void);
void ten(int);
void eleven(void);
void twelfth(int num);
void thirteen(void);
void fourteen(void);
void fifteen(int number);
void sixteen(int number);
void seventeen(int number);
void eighteen(void);
void nineteen(void);
void twenty(int number);
void twentyOne(int number);
void twentyTwo(void);
void twentyThree(int);
void twentyFour(int);
void twentyFive(int);
void twentySix(int);
void twentySeven(int);
void twentyEight(int);
void twentyNine(unsigned long long int);
void thirty(int);
void thirtyOne(void);
void thirtyTwo(void);
void thirtyThree(void);
void thirtyFour(void);
void thirtyFive(void);
void thirtySix(void);
void thirtySeven(void);
void thirtyEight(void);
void thirtyNine(void);
void fourty(void);
void fourtyOne(void);
void fourtyTwo(void);
void fourtyThree(void);
void fourtyFour(void);
void fourtyFive(void);
void fourtySix(void);
//void fourtySeven(void);
//void fourtyEight(void);
//void fourtyNine(void);